export const QuestClassList = [
  { value: "QuestBasic", label: "QuestBasic" },
  { value: "QuestMonsterModeClear", label: "QuestMonsterModeClear" },
  { value: "QuestEnterBattlePvPMode", label: "QuestEnterBattlePvPMode" },
  { value: "QuestEnterBattlePvPModeKO", label: "QuestEnterBattlePvPModeKO" },
  { value: "QuestEnterBattlePvPModeWin", label: "QuestEnterBattlePvPModeWin" },
  { value: "QuestPvEMonsterKill", label: "QuestPvEMonsterKill" },
  { value: "QuestGradeUP", label: "QuestGradeUP" },
  { value: "QuestTimeGrowthTry", label: "QuestTimeGrowthTry" },
  { value: "QuestTimeGrowthSuccess", label: "QuestTimeGrowthSuccess" },
  { value: "QuestPesoGrowthTry", label: "QuestPesoGrowthTry" },
  { value: "QuestFishingFailed", label: "QuestFishingFailed" },
  { value: "QuestFishingSuccess", label: "QuestFishingSuccess" },
  { value: "QuestFishingLevelUP", label: "QuestFishingLevelUP" },
  { value: "QuestFishingSellPeso", label: "QuestFishingSellPeso" },
  { value: "QuestFishingSuccessItem", label: "QuestFishingSuccessItem" },
  {
    value: "QuestBattlePvPModeAwardAcquire",
    label: "QuestBattlePvPModeAwardAcquire",
  },
  { value: "QuestSoldierPractice", label: "QuestSoldierPractice" },
  {
    value: "QuestExtraItemReinforceSuccess",
    label: "QuestExtraItemReinforceSuccess",
  },
  { value: "QuestSoldierLevelUP", label: "QuestSoldierLevelUP" },
  { value: "QuestOpenManual", label: "QuestOpenManual" },
  { value: "QuestLoginCount", label: "QuestLoginCount" },
  { value: "QuestEnterPlaza", label: "QuestEnterPlaza" },
  { value: "QuestGetPotion", label: "QuestGetPotion" },
  { value: "QuestTutorial", label: "QuestTutorial" },
  { value: "QuestPresentReceive", label: "QuestPresentReceive" },
  { value: "QuestCampJoin", label: "QuestCampJoin" },
  { value: "QuestEnterCampBattle", label: "QuestEnterCampBattle" },
  { value: "QuestCampBattleKO", label: "QuestCampBattleKO" },
  { value: "QuestCampBattleWin", label: "QuestCampBattleWin" },
  { value: "QuestCampSeasonReward", label: "QuestCampSeasonReward" },
  { value: "QuestAwardAcquire", label: "QuestAwardAcquire" },
  { value: "QuestPrisonerDrop", label: "QuestPrisonerDrop" },
  { value: "QuestPrisonerSave", label: "QuestPrisonerSave" },
  { value: "QuestBattleLevel", label: "QuestBattleLevel" },
  { value: "QuestAwardLevel", label: "QuestAwardLevel" },
  { value: "QuestContribute", label: "QuestContribute" },
  { value: "QuestDropKill", label: "QuestDropKill" },
  { value: "QuestMultiKill", label: "QuestMultiKill" },
  { value: "QuestPvPConsecution", label: "QuestPvPConsecution" },
  { value: "QuestCampConsecution", label: "QuestCampConsecution" },
  { value: "QuestEtcItemUse", label: "QuestEtcItemUse" },
  { value: "QuestEtcItemCnt", label: "QuestEtcItemCnt" },
  { value: "QuestRequestFriend", label: "QuestRequestFriend" },
  { value: "QuestMakeFriends", label: "QuestMakeFriends" },
  { value: "QuestModePlayTime", label: "QuestModePlayTime" },
  { value: "QuestStoneAttack", label: "QuestStoneAttack" },
  { value: "QuestKingAttack", label: "QuestKingAttack" },
  { value: "QuestCrownHoldTime", label: "QuestCrownHoldTime" },
  { value: "QuestBossModeBecomeBoss", label: "QuestBossModeBecomeBoss" },
  { value: "QuestBossModeBosswithKill", label: "QuestBossModeBosswithKill" },
  { value: "QuestMortmainSoldierCount", label: "QuestMortmainSoldierCount" },
  { value: "QuestHitCount", label: "QuestHitCount" },
  { value: "QuestDefenceCount", label: "QuestDefenceCount" },
  { value: "QuestPickItem", label: "QuestPickItem" },
  { value: "QuestCampLevel", label: "QuestCampLevel" },
  { value: "QuestBuyItem", label: "QuestBuyItem" },
  { value: "QuestMaxFriendSlot", label: "QuestMaxFriendSlot" },
  { value: "QuestRealTimeCount", label: "QuestRealTimeCount" },
  {
    value: "QuestFriendRecommendPlayTime",
    label: "QuestFriendRecommendPlayTime",
  },
  { value: "QuestQuickStartOption", label: "QuestQuickStartOption" },
  { value: "QuestBuySoldier", label: "QuestBuySoldier" },
  { value: "QuestPvETimeAttack", label: "QuestPvETimeAttack" },
  { value: "QuestSoccerBallHit", label: "QuestSoccerBallHit" },
  { value: "QuestSoccerGoal", label: "QuestSoccerGoal" },
  { value: "QuestSoccerAssist", label: "QuestSoccerAssist" },
  { value: "QuestSoccerSave", label: "QuestSoccerSave" },
  { value: "QuestExcavationTry", label: "QuestExcavationTry" },
  { value: "QuestExcavationLevelUP", label: "QuestExcavationLevelUP" },
  { value: "QuestExcavationSuccess", label: "QuestExcavationSuccess" },
  { value: "QuestExcavationFail", label: "QuestExcavationFail" },
  { value: "QuestExcavationTime", label: "QuestExcavationTime" },
  { value: "QuestScreenShot", label: "QuestScreenShot" },
  { value: "QuestMovieMode", label: "QuestMovieMode" },
  { value: "QuestMakeMovie", label: "QuestMakeMovie" },
  { value: "QuestExtraItemAcquire", label: "QuestExtraItemAcquire" },
  { value: "QuestExtraItemEquip", label: "QuestExtraItemEquip" },
  { value: "QuestExtraItemEquipKo", label: "QuestExtraItemEquipKo" },
  { value: "QuestGangsiKill", label: "QuestGangsiKill" },
  { value: "QuestGangsiHumanKill", label: "QuestGangsiHumanKill" },
  { value: "QuestGangsiAliveTime", label: "QuestGangsiAliveTime" },
  { value: "QuestGangsiHumanWin", label: "QuestGangsiHumanWin" },
  { value: "QuestHitAttackAttribute", label: "QuestHitAttackAttribute" },
  { value: "QuestGuildLevelMaintenance", label: "QuestGuildLevelMaintenance" },
  { value: "QuestGuildTeamWin", label: "QuestGuildTeamWin" },
  { value: "QuestGuildTeamPlayTime", label: "QuestGuildTeamPlayTime" },
  { value: "QuestPlayTimeRepeat", label: "QuestPlayTimeRepeat" },
  { value: "QuestDormantUser", label: "QuestDormantUser" },
  { value: "QuestDormantUserCustom", label: "QuestDormantUserCustom" },
  { value: "QuestDevKMove", label: "QuestDevKMove" },
  { value: "QuestPracticeSuccess", label: "QuestPracticeSuccess" },
] as const;
