import {
  ApertureIcon,
  DatabaseIcon,
  GiftIcon,
  LockKeyholeIcon,
  MedalIcon,
  SquareDashedIcon,
} from "lucide-react";

export const toolList = [
  {
    name: "LSC Converter",
    type: "tool",
    href: "/tools/lscconverter",
    description:
      "Simple tools to convert your GearDesign LSC file into DDS or convert your PNG files into DDS and LSC.",
    icon: ApertureIcon,
    active: false,
  },
  {
    name: "PNG To DDS",
    type: "tool",
    href: "/tools/png2dds",
    description: "Simple tools to convert your PNG file into DDS.",
    icon: ApertureIcon,
    active: false,
  },
  {
    name: "Quest Generator",
    type: "tool",
    href: "/tools/questgen",
    description: "a web service to create custom quest Lost saga.",
    icon: GiftIcon,
    active: false,
  },
  {
    name: "Medal Generator",
    type: "tool",
    href: "/tools/medalgen",
    description: "a web service to create custom medal Lost saga.",
    icon: MedalIcon,
    active: false,
  },
  {
    name: "ServerID Generator",
    type: "tool",
    href: "/tools/svridgen",
    description: "a web service to generate server id Lost saga.",
    icon: SquareDashedIcon,
    active: true,
  },
  {
    name: "IOP Password Generator",
    type: "tool",
    href: "/tools/passgen",
    description: "a web service to create encrypted IOP Password Lost saga.",
    icon: LockKeyholeIcon,
    active: true,
  },
  {
    name: "Icon Browser",
    type: "browser",
    href: "/tools/iconbrowser",
    description: "a web service to browse icon Lost saga.",
    icon: DatabaseIcon,
    active: true,
  },
  {
    name: "Item Browser",
    type: "browser",
    href: "/tools/itembrowser",
    description: "a web service to browse item Lost saga.",
    icon: DatabaseIcon,
    active: false,
  },
  {
    name: "Medal Browser",
    type: "browser",
    href: "/tools/medalbrowser",
    description: "a web service to browse medal Lost saga.",
    icon: DatabaseIcon,
    active: false,
  },
  {
    name: "Title Browser",
    type: "browser",
    href: "/tools/titlebrowser",
    description: "a web service to browse title Lost saga.",
    icon: DatabaseIcon,
    active: false,
  },
];
